# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

source 'https://git.coding.net/CocoaPods/Specs.git'

pod 'ReactiveCocoa', '2.5'

